

let nomeswork = [
	{nome: 'work 1', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 2', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 3', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 4', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 5', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 6', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 7', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 8', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 9', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 10', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 12', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 11', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 14', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 15', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 16', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 17', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 18', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 19', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 20', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 21', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 22', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 23', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 24', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 25', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 26', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 27', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 28', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 29', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 30', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
	{nome: 'work 31', hab: 'ctr', dias: 0, cargaHoraria: 0, turnos:[]},
]
